version: '1'
name: photo-prestiges
services:
  messagebroker:
    container_name: messagebroker
    image: rabbitmq:latest

  api-gateway:
    container_name: api-gateway
    build: 
      context: ./api-gateway
      dockerfile: dockerfile
    command: npm run dev
    ports: 
      - 3000:3000
    environment:
      - PORT=3000
      - USER_SERVER=user-service:3040
    volumes:
      - "./api-gateway:/usr/src/app/"

  auth:
    container_name: auth-service
    build: 
      context: ./services/auth
      dockerfile: dockerfile
    command: npm run dev
    ports: 
      - 3010:3010
    environment:
      - PORT=3010
      - MONGO_URL=mongodb://authdb:27017
      - RABBITMQ_URL=amqp://messagebroker
    depends_on:
      - authdb
    volumes:
      - "./services/auth:/usr/src/app/"

  competition:
    container_name: competition-service
    build: 
      context: ./services/competition
      dockerfile: dockerfile
    command: npm run dev
    ports: 
      - 3020:3020
    environment:
      - PORT=3020
      - MONGO_URL=mongodb://competitiondb:27017
      - RABBITMQ_URL=amqp://messagebroker
    depends_on:
      - competitiondb
    volumes:
      - "./services/competition:/usr/src/app/"

  image:
    container_name: image-service
    build: 
      context: ./services/image
      dockerfile: dockerfile
    command: npm run dev
    ports: 
      - 3030:3030
    environment:
      - PORT=3030
      - MONGO_URL=mongodb://imagedb:27017
      - RABBITMQ_URL=amqp://messagebroker
    depends_on:
      - imagedb
    volumes:
      - "./services/image:/usr/src/app/"

  user:
    container_name: user-service
    build: 
      context: ./services/user
      dockerfile: dockerfile
    command: npm run dev
    ports: 
      - 3040:3040
    environment:
      - PORT=3040
      - MONGO_URL=mongodb://userdb:27017
      - RABBITMQ_URL=amqp://messagebroker
    depends_on:
      - userdb
    volumes:
      - "./services/user:/usr/src/app/"

  authdb:
    container_name: authdb
    image: mongo:latest
    ports:
      - 27100:27017
    volumes:
      - auth_data:/data/db

  competitiondb:
    container_name: competitiondb
    image: mongo:latest
    ports:
      - 27200:27017
    volumes:
      - competition_data:/data/db

  imagedb:
    container_name: imagedb
    image: mongo:latest
    ports:
      - 27300:27017
    volumes:
      - image_data:/data/db

  userdb:
    container_name: userdb
    image: mongo:latest
    ports:
      - 27400:27017
    volumes:
      - user_data:/data/db

volumes:
  auth_data:
  competition_data:
  image_data:
  user_data:
